import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="min-h-screen transition-colors duration-500 bg-gradient-to-br from-rose-200 via-purple-100 to-indigo-100"
      >
        {children}
      </body>
    </html>
  );
}
